//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public class Employee
    {
        
        [Remote("CheckEmployeeId", "Employee", ErrorMessage = "Mã nhân viên ?ã t?n t?i")]
        public string emp_id { get; set; }
        public string emp_name { get; set; }
        public string emp_sex { get; set; }
        public string emp_position { get; set; }
        public string job_position { get; set; }
        public string supervisor_id { get; set; }
        public Nullable<int> company_id { get; set; }
    
        public virtual Company Company { get; set; }
    }
}
